quarkus:
  test:
    integration-test-profile: test
  http:
    port: 5975

"%test":
  quarkus:
    flyway:
      clean-at-start: true
    hibernate-orm:
      log:
        format-sql: true
        sql: true
        bind-parameters: true
    datasource:
      devservices:
        enabled: true
        port: 55432

