quarkus:
  test:
    integration-test-profile: test
  http:
    port: 5975
  flyway:
    migrate-at-start: true
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl

"%test":
  quarkus:
    flyway:
      clean-at-start: true
    hibernate-orm:
      log:
        format-sql: true
        sql: true
        bind-parameters: true

