CREATE
  SEQUENCE users_seq INCREMENT 1 START
    WITH 1 MINVALUE 1;

CREATE TABLE users
(
  id         BIGINT  NOT NULL,
  username   VARCHAR NOT NULL UNIQUE,
  password   VARCHAR NOT NULL,
  role       VARCHAR NOT NULL,
  PRIMARY KEY (id)
);
